# usage: python3 generate-overtakes-dict.py <overtakes-csv-file> <output-file-name-with-path>
import pandas as pd
import json
import sys

#### Added by Soham
infraPath = "simulator_input/"
simulator_out = "simulator_output/"
postprocessed_path = "postprocessed_files/"
####

# overtakes.csv was generated by find-overtakes-from-traversal-mp.py


ov_data=pd.read_csv(postprocessed_path + "overtakes.csv")
train_wise_ov={}

# for each train no. find how many trains have overtaken it
# check relevant train in separate function
for train in ov_data['Overtaken_T.No.'].unique():
    if str(train)[0]=='2':
        train_ov_data=ov_data[train==ov_data['Overtaken_T.No.']].copy()[['Overtaking_T.No.','stn_code']]
        if len(train_ov_data)>0:
            # this dict contains a list of pairs of overtaking trains and station code
            train_ov_data=train_ov_data.to_dict('records')
            train_wise_ov[str(int(train))]=str(len(train_ov_data))

#print(train_wise_ov)

with open(postprocessed_path + 'train_wise_overtakes.txt', 'w') as file:
     file.write(json.dumps(train_wise_ov).replace('"','\''))
     
     

